packages:
  - ./*
  - ./packages/*

catalogs:
  react18or19:
    '@types/react': ^18.3.12 || ^19.1.11
    '@types/react-dom': ^18.3.1 || ^19.1.7
    react: ^18.3.1 || ^19.1.1
    react-dom: ^18.3.1 || ^19.1.1
  react18:
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1
    react: ^18.3.1
    react-dom: ^18.3.1

catalog:
  '@babel/core': ^7.21.4
  '@carbon/icons-react': ^11.64.0
  '@carbon/react': ^1.88.0
  '@carbon/styles': ^1.87.0
  '@carbon/themes': ^11.57.0
  '@emotion/css': ^11.11.0
  '@emotion/react': ^11.13.3
  '@emotion/styled': ^11.11.0
  '@eslint/js': ^9.17.0
  '@grafana/data': ^12.1.0
  '@grafana/eslint-config': ^7.0.0
  '@grafana/plugin-ui': ^0.10.10
  '@grafana/runtime': ^12.1.0
  '@grafana/schema': ^12.1.0
  '@grafana/tsconfig': ^2.0.0
  '@grafana/ui': ^12.1.0
  '@swc/core': ^1.10.9
  '@swc/helpers': ^0.5.0
  '@swc/jest': ^0.2.26
  '@swc/plugin-emotion': ^8.4.0
  '@tailwindcss/vite': ^4.1.12
  '@tanstack/react-query-devtools': ^4.24.4
  '@testing-library/jest-dom': 6.1.4
  '@testing-library/react': 14.0.0
  '@types/glob': ^8.0.0
  '@types/jest': ^29.5.0
  '@types/lodash': ^4.14.194
  '@types/node': ^20
  '@types/react-router-dom': ^5.3.3
  '@types/testing-library__jest-dom': 5.14.8
  '@typescript-eslint/eslint-plugin': ^5.59.5
  '@typescript-eslint/parser': ^5.59.5
  '@vitejs/plugin-react-swc': ^3.5.0
  copy-webpack-plugin: ^11.0.0
  css-loader: ^6.7.3
  eslint: ^8.57.1
  eslint-config-prettier: ^8.3.0
  eslint-import-resolver-typescript: ^3.6.1
  eslint-plugin-deprecation: ^2.0.0
  eslint-plugin-import: ^2.29.1
  eslint-plugin-jsdoc: ^44.0.0
  eslint-plugin-prettier: ^4.0.0
  eslint-plugin-react: ^7.35.0
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.16
  eslint-webpack-plugin: ^4.0.1
  fork-ts-checker-webpack-plugin: ^8.0.0
  glob: ^10.2.7
  globals: ^15.14.0
  identity-obj-proxy: 3.0.0
  imports-loader: ^5.0.0
  jest: ^29.5.0
  jest-environment-jsdom: ^29.5.0
  lodash: ^4.14.188
  npm-dummy-package: '1.0.1'
  prettier: ^3.0
  prettier-plugin-tailwindcss: ^0.6.11
  replace-in-file-webpack-plugin: ^1.0.6
  rxjs: 7.8.1
  sass: 1.63.2
  sass-loader: 13.3.1
  style-loader: 3.3.3
  swc-loader: ^0.2.6
  tailwindcss: ^4.0.0
  terser-webpack-plugin: ^5.3.10
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tslib: 2.5.3
  typescript: ^5.7.2
  typescript-eslint: ^8.18.2
  vite-plugin-dts: ^4.5.0
  vite-tsconfig-paths: ^5.1.4
  webpack: ^5.94.0
  webpack-cli: ^5.1.4
  webpack-livereload-plugin: ^3.0.2
  webpack-subresource-integrity: ^5.1.0
  webpack-virtual-modules: ^0.6.2
